/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yw283_checkerboard;

import javafx.scene.layout.AnchorPane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;

/**
 *
 * @author yq.wang
 */
public class Checkerboard {
    private AnchorPane pane;
    private int numRows;
    private int numCols;
    private double boardWidth;
    private double boardHeight;
    private double rectWidth;
    private double rectHeight;
    private Color lightColor;
    private Color darkColor;
    
    //first constructor
    public Checkerboard (int numRows, int numCols, double boardWidth, double boardHeight) { 
        this.pane = new AnchorPane(); 
        this.numRows = numRows;
        this.numCols = numCols;
        this.boardWidth = boardWidth;
        this.boardHeight = boardHeight;
    }
    
    //second constructor
    public Checkerboard (int numRows, int numCols, double boardWidth, double boardHeight, Color lightColor, Color darkColor) {
         this(numRows, numCols, boardWidth, boardHeight);
         this.lightColor = lightColor;
         this.darkColor = darkColor;
    }
    
    //builds the board UI and returns an AnchorPane as the root object
    public AnchorPane build() {
        rectWidth = Math.ceil(boardWidth / numCols);
        rectHeight = Math.ceil(boardHeight / numRows);

        for (int row = 0; row < numRows; row++) 
            for (int col = 0; col < numCols; col++) 
            {   
                Rectangle rect = new Rectangle(rectWidth, rectHeight);
                
                if((col%2==1&&row%2==1)||(col%2==0&&row%2==0))
                {
                    rect.setFill(lightColor);
                }
                else
                {
                    rect.setFill(darkColor);
                }
                
                pane.getChildren().addAll(rect);
                AnchorPane.setTopAnchor(rect, row*rectHeight);
                AnchorPane.setLeftAnchor(rect, col*rectWidth);    
            }
        
        return pane;
    }
    
    //returns the AnchorPane generated by build() or null if one hasn’t been built yet
    public AnchorPane getBoard() {
        if(pane != null)
            return pane;
        else
            return null;
    }
    
    //getters and setters
    public int getNumRows() {
        return numRows;
    }
      
    public int getNumCols() {
        return numCols;
    }
        
    public double getWidth() {
        return boardWidth;
    }
        
    public double getHeight() {
        return boardHeight;
    }
        
    public Color getLightColor() {
        return lightColor;
    }
        
    public Color getDarkColor() {
        return darkColor;
    }
        
    public double getRectangleWidth() {
        return rectWidth;
    }
        
    public double getRectangleHeight() {
        return rectHeight;
    }  
}


